# Generated by Django 3.2.4 on 2021-06-16 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('full_name', models.CharField(max_length=50)),
                ('bot_state', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('number', models.IntegerField(default=1)),
                ('month', models.IntegerField(default=12)),
                ('protsent', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('language', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backendm.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='magazin/image')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendm.category')),
            ],
        ),
        migrations.CreateModel(
            name='ShopCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('percent', models.IntegerField(default=0)),
                ('month', models.IntegerField(default=12)),
                ('payments', models.IntegerField(default=0)),
                ('month_pay', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendm.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendm.botuser')),
            ],
        ),
        migrations.CreateModel(
            name='OrderCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.CharField(max_length=200)),
                ('count', models.IntegerField(default=0)),
                ('protsent', models.IntegerField(default=0)),
                ('month', models.IntegerField(default=12)),
                ('payments', models.IntegerField(default=0)),
                ('month_pay', models.IntegerField(default=0)),
                ('all_price', models.IntegerField(default=0)),
                ('check', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendm.botuser')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.CharField(max_length=200)),
                ('count', models.IntegerField(default=0)),
                ('all_price', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Yangi 🆕', 'Yangi 🆕'), ('Tekshirilmoqda ⏳', 'Tekshirilmoqda ⏳'), ('Tayyor ✅', 'Tayyor ✅')], default='Yangi 🆕', max_length=50)),
                ('check', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendm.botuser')),
            ],
        ),
    ]
