# Generated by Django 3.2.4 on 2021-06-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='number1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='image'),
        ),
    ]
