# Generated by Django 3.2.4 on 2021-06-29 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendm', '0002_auto_20210616_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcard',
            name='status',
            field=models.CharField(choices=[('Tezkor Xarid 🛍', 'Tezkor Xarid 🛍'), ('Bo`lib to`lash', 'Bo`lib to`lash ⏳')], default='Tezkor Xarid 🛍', max_length=50),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='month',
            field=models.IntegerField(default=3),
        ),
        migrations.CreateModel(
            name='ShopCardOrderCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.CharField(max_length=200)),
                ('count', models.IntegerField(default=0)),
                ('protsent', models.IntegerField(default=0)),
                ('month', models.IntegerField(default=12)),
                ('payments', models.IntegerField(default=0)),
                ('month_pay', models.IntegerField(default=0)),
                ('all_price', models.IntegerField(default=0)),
                ('check', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendm.botuser')),
            ],
        ),
    ]
