# Generated by Django 3.2.4 on 2021-06-29 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendm', '0003_auto_20210629_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopcard',
            name='month',
        ),
        migrations.RemoveField(
            model_name='shopcard',
            name='month_pay',
        ),
        migrations.RemoveField(
            model_name='shopcard',
            name='payments',
        ),
        migrations.RemoveField(
            model_name='shopcard',
            name='percent',
        ),
    ]
