# Generated by Django 3.2.4 on 2021-06-29 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendm', '0004_auto_20210629_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcard',
            name='month',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='shopcard',
            name='month_pay',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shopcard',
            name='payments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shopcard',
            name='percent',
            field=models.IntegerField(default=0),
        ),
    ]
