# Generated by Django 3.2.4 on 2021-07-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendm', '0006_alter_shopcard_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcard',
            name='chec',
            field=models.BooleanField(default=False),
        ),
    ]
